openapi: 3.0.0
info:
  title: Events API
  version: 1.0.0
paths:
  /search:
    get:
      tags:
        - Events
      parameters:
        - name: starts_at
          in: query
          schema:
            type: string
            format: date
            default: 2017-07-21T17:32:28Z
          required: true
          description: Return only events that start after this date
        - name: ends_at
          in: query
          schema:
            type: string
            format: date-time
            default: 2021-07-21T17:32:28Z
          required: true
          description: Return only events that finish before this date
      responses:
        200:
          description: List of plans
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      events:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: string
                              default: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
                            title:
                              type: string
                              default: "Event title"
                            start_date:
                              type: string
                            start_time:
                              type: string
                            end_date:
                              type: string
                            end_time:
                              type: string
                            min_price:
                              type: number
                            max_price:
                              type: number
                  error:
                    type: object
                    nullable: true
                    properties:
                      code:
                        type: string
                      message:
                        type: string
        400:
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                      message:
                        type: string
                  data:
                    type: null
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                      message:
                        type: string