services:

  api:
      build:
        context: ../..
        dockerfile: ops/docker/Dockerfile.local
      ports:
        - "5000:5000"
      volumes:
        - ../../:/app
      environment:
        FLASK_APP: run.py
        FLASK_ENV: development
        FLASK_DEBUG: 1
        FLASK_RUN_HOST:
        POSTGRES_DB: fever_db
        POSTGRES_USER: fever_user
        POSTGRES_PASSWORD: fever_pass
        POSTGRES_HOST: db
        POSTGRES_PORT: 5432
        REDIS_HOST: redis
        REDIS_PORT: 6379

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: fever_db
      POSTGRES_USER: fever_user
      POSTGRES_PASSWORD: fever_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  pgdata: