services:
  
  fetcher:
    build:
      context: ../..
      dockerfile: ops/docker/Dockerfile-fetcher.local
    restart: always
    environment:
        FLASK_APP: fetch.py
        FLASK_ENV: development
        FLASK_DEBUG: 1
        FLASK_RUN_HOST: