FROM python:3.10-slim

WORKDIR /app

RUN pip install --no-cache-dir poetry

RUN ls -la

COPY pyproject.toml poetry.lock /app/

RUN poetry config virtualenvs.create false && \
    poetry install --no-dev --no-interaction --no-ansi

COPY . .

EXPOSE 5000

CMD ["poetry", "run", "flask", "run", "--host=0.0.0.0"]